language: go
os:
  - windows
  - linux
  - osx
go:
  - "1.12"
env:
  global:
    - GO111MODULE=on
install:
  - go mod download
  - go get github.com/rakyll/gotest
script:
  - COVER_PKGS=$(go list ./... | grep -v testutils | tr '\n' ',')
  - gotest -race -v ./... -tags integration -coverpkg=$COVER_PKGS -covermode=atomic -coverprofile=coverage.out -bench . -cpu 1,4
after_success:
  - bash <(curl -s https://codecov.io/bash)
