language: go
os:
  - windows
  - linux
  - osx
go:
  - "1.12"
env:
  global:
    - GO111MODULE=on
install:
  - go mod download
  - go get github.com/rakyll/gotest
  - go get github.com/mattn/goveralls
script:
  - COVER_PKGS=$(go list ./... | grep -v testutils | tr '\n' ',')
  - gotest -race -v ./... -tags integration -coverpkg=$COVER_PKGS -covermode=atomic -coverprofile=coverage.out -bench . -cpu 1,4
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN || true'
  - bash <(curl -s https://codecov.io/bash)
