language: go
os:
  - windows
  - linux
  - osx
go:
  - "1.12"
env:
  global:
    - GO111MODULE=on
install:
  - go mod download
  - go get github.com/mattn/goveralls
script:
  - go test -v ./... -tags integration -coverpkg=./... -covermode=count -coverprofile=coverage.out -bench . -cpu 1,4
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN || true'
